const comfortingQuotes = [
  "Even the darkest night will end and the sun will rise.",
  "You are stronger than you know.",
  "It's okay to take a break; you are doing the best you can.",
  "This too shall pass.",
  "Every storm runs out of rain.",
  "You are not alone in this.",
  "Breathe. You're going to be okay.",
  "Healing is a process, not a race.",
  "You are enough, just as you are.",
  "One day at a time, one step at a time.",
  "You are allowed to feel what you're feeling.",
  "It's okay to not be okay all the time.",
  "You are capable of more than you can imagine.",
  "It's okay to ask for help.",
  "Let go of what you cannot change.",
  "You are braver than you believe.",
  "Everything is temporary.",
  "You are loved more than you know.",
  "Your feelings are valid.",
  "Keep going; you are on your way.",
  "There is light at the end of the tunnel.",
  "You are deserving of peace and happiness.",
  "Be kind to yourself.",
  "You are not your mistakes.",
  "Take things one day at a time.",
  "You are doing better than you think.",
  "It's okay to rest and recharge.",
  "This moment does not define you.",
  "You are growing through what you are going through.",
  "You are resilient and resourceful.",
  "Your journey is unique, and so are you.",
  "You are not alone in your struggles.",
  "Allow yourself to be gentle with your soul.",
  "You have the strength to get through this.",
  "You are worthy of love and care.",
  "Your story isn't over yet.",
  "You are more than enough.",
  "Trust the process, even when it's hard.",
  "You are allowed to set boundaries.",
  "You are capable of handling whatever comes your way.",
  "You are not defined by your past.",
  "You are deserving of all the good things in life.",
  "Your heart is stronger than you realize.",
  "You are not a burden.",
  "You have a purpose, even if you can't see it yet.",
  "You are worthy of your dreams.",
  "It's okay to let go of the things that weigh you down.",
  "You are important and your presence matters.",
  "You have the power to create change.",
  "You are a work in progress, and that's okay.",
  "You are surrounded by love, even when it feels distant.",
  "You are allowed to grow and change.",
  "You are doing your best, and that is enough.",
  "You have the power to rewrite your story.",
  "You are not alone in your pain.",
  "You are a survivor.",
  "You are loved, even when you feel unlovable.",
  "You are worthy of compassion, especially from yourself.",
  "You are more capable than you think.",
  "Your strength is within you, always.",
  "You are worthy of rest and recovery.",
  "You are not alone in your journey.",
  "You have the strength to rise above.",
  "You are deserving of joy and peace.",
  "You are enough, just as you are.",
  "You are allowed to take up space.",
  "You are stronger than you give yourself credit for.",
  "You are not defined by your struggles.",
  "You are capable of overcoming this.",
  "You are loved more than you know.",
  "You are worthy of forgiveness, especially from yourself.",
  "You are not your thoughts.",
  "You are allowed to be a work in progress.",
  "You are enough, today and always.",
  "You are not alone in your feelings.",
  "You are more resilient than you realize.",
  "You are capable of achieving great things.",
  "You are worthy of kindness and love.",
  "You are not a failure; you are learning.",
  "You are allowed to feel how you feel.",
  "You are not alone in this world.",
  "You are a beacon of light, even in the darkness.",
  "You are worthy of everything good.",
  "You are stronger than you think.",
  "You are not defined by your circumstances.",
  "You are capable of moving forward.",
  "You are worthy of being loved and cherished.",
  "You are more than your struggles.",
  "You are allowed to be human.",
  "You are not alone in your fight.",
  "You are a beautiful soul, inside and out.",
  "You are worthy of healing and happiness.",
  "You are not your mistakes; you are your recovery.",
  "You are strong, even when you feel weak.",
  "You are enough, just as you are.",
  "You are capable of so much more than you know.",
  "You are worthy of all the love in the world.",
  "You are not alone; we are in this together.",
];

module.exports = { comfortingQuotes };
