const inspirationalQuotes = [
  "The best way to get started is to quit talking and begin doing.",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
  "Don’t let yesterday take up too much of today.",
  "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Do not wait to strike till the iron is hot, but make it hot by striking.",
  "The only way to do great work is to love what you do.",
  "In the middle of every difficulty lies opportunity.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "You must be the change you wish to see in the world.",
  "The journey of a thousand miles begins with one step.",
  "Believe you can and you’re halfway there.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Act as if what you do makes a difference. It does.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "The only impossible journey is the one you never begin.",
  "Dream big and dare to fail.",
  "Your time is limited, don’t waste it living someone else’s life.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Opportunities don't happen. You create them.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "You do not find the happy life. You make it.",
  "The only person you are destined to become is the person you decide to be.",
  "You are never too old to set another goal or to dream a new dream.",
  "Start where you are. Use what you have. Do what you can.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream it. Believe it. Build it.",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work, the more opportunities you create.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Work hard in silence. Let your success be your noise.",
  "Dream it. Believe it. Pursue it.",
  "Don’t wait for opportunity. Create it.",
  "The secret of getting ahead is getting started.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Work for it. Pay the price.",
  "Success is what happens after you have survived all your mistakes.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Everything you need is already inside you.",
  "The best preparation for tomorrow is doing your best today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You are capable of more than you know.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "The way to get started is to quit talking and begin doing.",
  "Do what you can, with what you have, where you are.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Your life does not get better by chance, it gets better by change.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work, the more opportunities you create.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Work hard in silence. Let your success be your noise.",
  "Dream it. Believe it. Pursue it.",
  "Don’t wait for opportunity. Create it.",
  "The secret of getting ahead is getting started.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Work for it. Pay the price.",
  "Success is what happens after you have survived all your mistakes.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Everything you need is already inside you.",
  "The best preparation for tomorrow is doing your best today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You are capable of more than you know.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "The way to get started is to quit talking and begin doing.",
  "Do what you can, with what you have, where you are.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Your life does not get better by chance, it gets better by change.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work, the more opportunities you create.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Work hard in silence. Let your success be your noise.",
  "Dream it. Believe it. Pursue it.",
  "Don’t wait for opportunity. Create it.",
  "The secret of getting ahead is getting started.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Work for it. Pay the price.",
  "Success is what happens after you have survived all your mistakes.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Everything you need is already inside you.",
  "The best preparation for tomorrow is doing your best today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You are capable of more than you know.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "The way to get started is to quit talking and begin doing.",
  "Do what you can, with what you have, where you are.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Your life does not get better by chance, it gets better by change.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work, the more opportunities you create.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Work hard in silence. Let your success be your noise.",
  "Dream it. Believe it. Pursue it.",
  "Don’t wait for opportunity. Create it.",
  "The secret of getting ahead is getting started.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Work for it. Pay the price.",
  "Success is what happens after you have survived all your mistakes.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Everything you need is already inside you.",
  "The best preparation for tomorrow is doing your best today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You are capable of more than you know.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "The way to get started is to quit talking and begin doing.",
  "Do what you can, with what you have, where you are.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Your life does not get better by chance, it gets better by change.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "What we think, we become.",
  "The only way to do great work is to love what you do.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "Your time is limited, don't waste it living someone else's life.",
  "You miss 100% of the shots you don't take.",
  "Whether you think you can or you think you can’t, you’re right.",
  "The best way to predict the future is to create it.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "The only place where success comes before work is in the dictionary.",
  "Believe you can and you're halfway there.",
  "Challenges are what make life interesting, overcoming them is what makes life meaningful.",
  "Don’t count the days, make the days count.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "You can, you should, and if you’re brave enough to start, you will.",
  "Do one thing every day that scares you.",
  "The difference between ordinary and extraordinary is that little extra.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Success is not in what you have, but who you are.",
  "The best revenge is massive success.",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
  "Don’t be afraid to give up the good to go for the great.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Success is not in what you have, but who you are.",
  "The road to success is dotted with many tempting parking spaces.",
  "You have to learn the rules of the game. And then you have to play better than anyone else.",
  "It is our choices that show what we truly are, far more than our abilities.",
  "I find that the harder I work, the more luck I seem to have.",
  "Don’t let yesterday take up too much of today.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You don't have to be great to start, but you have to start to be great.",
  "The secret of getting ahead is getting started.",
  "If you're going through hell, keep going.",
  "Perseverance is not a long race; it is many short races one after the other.",
  "We become what we think about.",
  "The way to get started is to quit talking and begin doing.",
  "If opportunity doesn’t knock, build a door.",
  "You are never too old to set another goal or to dream a new dream.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Opportunities don't happen. You create them.",
  "To be successful, you must accept all challenges that come your way. You can't just accept the ones you like.",
  "Things work out best for those who make the best of how things work out.",
  "Success seems to be connected with action. Successful people keep moving. They make mistakes but they don’t quit.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Don’t be afraid to give up the good to go for the great.",
  "You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "If you can dream it, you can do it.",
  "A person who never made a mistake never tried anything new.",
  "Success is not in what you have, but who you are.",
  "There are no shortcuts to any place worth going.",
  "What seems to us as bitter trials are often blessings in disguise.",
  "Don’t count the days, make the days count.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "Action is the foundational key to all success.",
  "In order to succeed, your desire for success should be greater than your fear of failure.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "The difference between who you are and who you want to be is what you do.",
  "The best way to succeed in this world is to act on the advice you give to others.",
  "The future depends on what you do today.",
  "Success is not just about making money. It's about making a difference.",
  "The key to success is to focus on goals, not obstacles.",
  "The only place where success comes before work is in the dictionary.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Success isn’t always about greatness. It’s about consistency. Consistent hard work gains success. Greatness will come.",
  "Don’t wish it were easier. Wish you were better.",
  "The best preparation for tomorrow is doing your best today.",
  "Success is what happens after you have survived all your mistakes.",
  "Success is how high you bounce when you hit bottom.",
  "Don’t let what you cannot do interfere with what you can do.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The successful warrior is the average man, with laser-like focus.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "There is no substitute for hard work.",
  "Believe you can and you’re halfway there.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Action is the foundational key to all success.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "The best preparation for tomorrow is doing your best today.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Do not wait; the time will never be ‘just right.’ Start where you stand, and work with whatever tools you may have at your command.",
  "Your big opportunity may be right where you are now.",
  "The future depends on what we do in the present.",
  "Your life does not get better by chance, it gets better by change.",
  "Success is how high you bounce when you hit bottom.",
  "The secret of success is to do the common thing uncommonly well.",
  "Successful people do what unsuccessful people are not willing to do. Don’t wish it were easier; wish you were better.",
  "Do not let what you cannot do interfere with what you can do.",
  "Success usually comes to those who are too busy to be looking for it.",
  "It does not matter how slowly you go, as long as you do not stop.",
  "Opportunities are usually disguised as hard work, so most people don’t recognize them.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "It always seems impossible until it’s done.",
];

module.exports = { inspirationalQuotes };
