const inspirationalQuotes = [
  "The best way to get started is to quit talking and begin doing.",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
  "Don’t let yesterday take up too much of today.",
  "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Do not wait to strike till the iron is hot, but make it hot by striking.",
  "The only way to do great work is to love what you do.",
  "In the middle of every difficulty lies opportunity.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "You must be the change you wish to see in the world.",
  "The journey of a thousand miles begins with one step.",
  "Believe you can and you’re halfway there.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Act as if what you do makes a difference. It does.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "The only impossible journey is the one you never begin.",
  "Dream big and dare to fail.",
  "Your time is limited, don’t waste it living someone else’s life.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Opportunities don't happen. You create them.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "You do not find the happy life. You make it.",
  "The only person you are destined to become is the person you decide to be.",
  "You are never too old to set another goal or to dream a new dream.",
  "Start where you are. Use what you have. Do what you can.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream it. Believe it. Build it.",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work, the more opportunities you create.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Work hard in silence. Let your success be your noise.",
  "Dream it. Believe it. Pursue it.",
  "Don’t wait for opportunity. Create it.",
  "The secret of getting ahead is getting started.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Work for it. Pay the price.",
  "Success is what happens after you have survived all your mistakes.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Everything you need is already inside you.",
  "The best preparation for tomorrow is doing your best today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You are capable of more than you know.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "The way to get started is to quit talking and begin doing.",
  "Do what you can, with what you have, where you are.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Your life does not get better by chance, it gets better by change.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work, the more opportunities you create.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Work hard in silence. Let your success be your noise.",
  "Dream it. Believe it. Pursue it.",
  "Don’t wait for opportunity. Create it.",
  "The secret of getting ahead is getting started.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Work for it. Pay the price.",
  "Success is what happens after you have survived all your mistakes.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Everything you need is already inside you.",
  "The best preparation for tomorrow is doing your best today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You are capable of more than you know.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "The way to get started is to quit talking and begin doing.",
  "Do what you can, with what you have, where you are.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Your life does not get better by chance, it gets better by change.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work, the more opportunities you create.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Work hard in silence. Let your success be your noise.",
  "Dream it. Believe it. Pursue it.",
  "Don’t wait for opportunity. Create it.",
  "The secret of getting ahead is getting started.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Work for it. Pay the price.",
  "Success is what happens after you have survived all your mistakes.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Everything you need is already inside you.",
  "The best preparation for tomorrow is doing your best today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You are capable of more than you know.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "The way to get started is to quit talking and begin doing.",
  "Do what you can, with what you have, where you are.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Your life does not get better by chance, it gets better by change.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work, the more opportunities you create.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Work hard in silence. Let your success be your noise.",
  "Dream it. Believe it. Pursue it.",
  "Don’t wait for opportunity. Create it.",
  "The secret of getting ahead is getting started.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Work for it. Pay the price.",
  "Success is what happens after you have survived all your mistakes.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Everything you need is already inside you.",
  "The best preparation for tomorrow is doing your best today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You are capable of more than you know.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "The way to get started is to quit talking and begin doing.",
  "Do what you can, with what you have, where you are.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Your life does not get better by chance, it gets better by change.",
];

module.exports = { inspirationalQuotes };
