const standardQuotes = [
  '"You must be the change you wish to see in the world." – Mahatma Gandhi',
  '"Opportunities don\'t happen. You create them." – Chris Grosser',
  '"The only impossible journey is the one you never begin." – Tony Robbins',
  '"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart." – Roy T. Bennett',
  '"It always seems impossible until it’s done." – Nelson Mandela',
  '"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact." – William James',
  '"You have within you right now, everything you need to deal with whatever the world can throw at you." – Brian Tracy',
  '"The only way to achieve the impossible is to believe it is possible." – Charles Kingsleigh',
  '"Success is going from failure to failure without losing your enthusiasm." – Winston Churchill',
  '"The only person you are destined to become is the person you decide to be." – Ralph Waldo Emerson',
  '"To live is the rarest thing in the world. Most people exist, that is all." – Oscar Wilde',
  '"Go confidently in the direction of your dreams. Live the life you have imagined." – Henry David Thoreau',
  '"You must do the things you think you cannot do." – Eleanor Roosevelt',
  '"Everything you can imagine is real." – Pablo Picasso',
  '"The mind is everything. What you think you become." – Buddha',
  '"Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. The world is full of educated derelicts. The slogan ‘Press On’ has solved and always will solve the problems of the human race." – Calvin Coolidge',
  '"Don’t let what you cannot do interfere with what you can do." – John Wooden',
  '"The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it." – Jordan Belfort',
  '"The most wasted of days is one without laughter." – E.E. Cummings',
  '"To handle yourself, use your head; to handle others, use your heart." – Eleanor Roosevelt',
  '"The difference between ordinary and extraordinary is that little extra." – Jimmy Johnson',
  '"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle." – Christian D. Larson',
  '"In three words I can sum up everything I\'ve learned about life: it goes on." – Robert Frost',
  '"Life is either a daring adventure or nothing at all." – Helen Keller',
  '"Success doesn’t come from what you do occasionally, it comes from what you do consistently." – Marie Forleo',
  '"The best way out is always through." – Robert Frost',
  '"It is never too late to be what you might have been." – George Eliot',
  '"The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well." – Ralph Waldo Emerson',
  '"In order to succeed, we must first believe that we can." – Nikos Kazantzakis',
  '"We may encounter many defeats but we must not be defeated." – Maya Angelou',
  '"You only live once, but if you do it right, once is enough." – Mae West',
  '"The best time to plant a tree was 20 years ago. The second best time is now." – Chinese Proverb',
  '"Your passion is waiting for your courage to catch up." – Isabelle Lafleche',
  '"A goal is not always meant to be reached, it often serves simply as something to aim at." – Bruce Lee',
  '"The only person you should try to be better than is the person you were yesterday." – Anonymous',
  '"Everything has beauty, but not everyone can see." – Confucius',
  '"Success usually comes to those who are too busy to be looking for it." – Henry David Thoreau',
  '"Your life does not get better by chance, it gets better by change." – Jim Rohn',
  '"The best way to predict the future is to create it." – Peter Drucker',
  '"We can’t help everyone, but everyone can help someone." – Ronald Reagan',
  '"You don’t have to be perfect to be amazing." – Anonymous',
  '"The only way to make sense out of change is to plunge into it, move with it, and join the dance." – Alan Watts',
  '"Be yourself; everyone else is already taken." – Oscar Wilde',
  '"Your time is limited, so don’t waste it living someone else’s life." – Steve Jobs',
  '"Everything has its beauty, but not everyone can see it." – Confucius',
  '"The only limit to our realization of tomorrow is our doubts of today." – Franklin D. Roosevelt',
  '"Do what you can, with what you have, where you are." – Theodore Roosevelt',
  '"You can’t go back and change the beginning, but you can start where you are and change the ending." – C.S. Lewis',
  '"The future belongs to those who believe in the beauty of their dreams." – Eleanor Roosevelt',
  '"Life is what happens when you’re busy making other plans." – John Lennon',
  "\"In the end, it's not the years in your life that count. It's the life in your years.\" – Abraham Lincoln",
  '"Everything you’ve ever wanted is on the other side of fear." – George Addair',
  '"What lies behind us and what lies before us are tiny matters compared to what lies within us." – Ralph Waldo Emerson',
  '"You are never too old to set another goal or to dream a new dream." – C.S. Lewis',
  '"The only way to do great work is to love what you do." – Steve Jobs',
  '"The best way to get started is to quit talking and begin doing." – Walt Disney',
  '"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful." – Albert Schweitzer',
  '"Believe you can and you\'re halfway there." – Theodore Roosevelt',
  '"It does not matter how slowly you go as long as you do not stop." – Confucius',
  '"The best revenge is massive success." – Frank Sinatra',
  '"You must be the change you wish to see in the world." – Mahatma Gandhi',
  '"Opportunities don\'t happen. You create them." – Chris Grosser',
  '"The only impossible journey is the one you never begin." – Tony Robbins',
  '"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart." – Roy T. Bennett',
  '"It always seems impossible until it’s done." – Nelson Mandela',
  '"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact." – William James',
  '"You have within you right now, everything you need to deal with whatever the world can throw at you." – Brian Tracy',
  '"The only way to achieve the impossible is to believe it is possible." – Charles Kingsleigh',
  '"Success is going from failure to failure without losing your enthusiasm." – Winston Churchill',
  '"The only person you are destined to become is the person you decide to be." – Ralph Waldo Emerson',
  '"To live is the rarest thing in the world. Most people exist, that is all." – Oscar Wilde',
  '"Go confidently in the direction of your dreams. Live the life you have imagined." – Henry David Thoreau',
  '"You must do the things you think you cannot do." – Eleanor Roosevelt',
  '"Everything you can imagine is real." – Pablo Picasso',
  '"The mind is everything. What you think you become." – Buddha',
  '"Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. The world is full of educated derelicts. The slogan ‘Press On’ has solved and always will solve the problems of the human race." – Calvin Coolidge',
  '"Don’t let what you cannot do interfere with what you can do." – John Wooden',
  '"The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it." – Jordan Belfort',
  '"The most wasted of days is one without laughter." – E.E. Cummings',
  '"To handle yourself, use your head; to handle others, use your heart." – Eleanor Roosevelt',
  '"The difference between ordinary and extraordinary is that little extra." – Jimmy Johnson',
  '"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle." – Christian D. Larson',
  '"In three words I can sum up everything I\'ve learned about life: it goes on." – Robert Frost',
  '"Life is either a daring adventure or nothing at all." – Helen Keller',
  '"Success doesn’t come from what you do occasionally, it comes from what you do consistently." – Marie Forleo',
  '"The best way out is always through." – Robert Frost',
  '"It is never too late to be what you might have been." – George Eliot',
  '"The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well." – Ralph Waldo Emerson',
  '"Success is not final, failure is not fatal: It is the courage to continue that counts." – Winston Churchill',
  '"Life is 10% what happens to us and 90% how we react to it." – Charles R. Swindoll',
  '"Act as if what you do makes a difference. It does." – William James',
  '"The best way to predict your future is to create it." – Abraham Lincoln',
  '"Believe in your infinite potential. Your only limitations are those you set upon yourself." – Roy T. Bennett',
  '"Keep your face always toward the sunshine—and shadows will fall behind you." – Walt Whitman',
  '"You cannot swim for new horizons until you have courage to lose sight of the shore." – William Faulkner',
  '"The only limit to our realization of tomorrow will be our doubts of today." – Franklin D. Roosevelt',
  '"It does not matter how slowly you go as long as you do not stop." – Confucius',
  '"The only thing we have to fear is fear itself." – Franklin D. Roosevelt',
  '"I can’t change the direction of the wind, but I can adjust my sails to always reach my destination." – Jimmy Dean',
  '"Start where you are. Use what you have. Do what you can." – Arthur Ashe',
  '"We are what we repeatedly do. Excellence, then, is not an act, but a habit." – Aristotle',
  '"Life is not measured by the number of breaths we take, but by the moments that take our breath away." – Maya Angelou',
  '"You miss 100% of the shots you don’t take." – Wayne Gretzky',
  '"Hardships often prepare ordinary people for an extraordinary destiny." – C.S. Lewis',
  '"The future belongs to those who believe in the beauty of their dreams." – Eleanor Roosevelt',
  '"What lies behind us and what lies before us are tiny matters compared to what lies within us." – Ralph Waldo Emerson',
  '"The greatest glory in living lies not in never falling, but in rising every time we fall." – Nelson Mandela',
  '"If life were predictable it would cease to be life, and be without flavor." – Eleanor Roosevelt',
  '"Do not go where the path may lead, go instead where there is no path and leave a trail." – Ralph Waldo Emerson',
  '"Keep your eyes on the stars and your feet on the ground." – Theodore Roosevelt',
  '"In the end, we will remember not the words of our enemies, but the silence of our friends." – Martin Luther King Jr.',
  '"Don’t count the days, make the days count." – Muhammad Ali',
  '"If you’re going through hell, keep going." – Winston Churchill',
  '"Success is not how high you have climbed, but how you make a positive difference to the world." – Roy T. Bennett',
  '"You are enough just as you are." – Meghan Markle',
  '"Whether you think you can or you think you can’t, you’re right." – Henry Ford',
  '"Do one thing every day that scares you." – Eleanor Roosevelt',
  '"Don’t watch the clock; do what it does. Keep going." – Sam Levenson',
  '"The secret of getting ahead is getting started." – Mark Twain',
  '"The question isn’t who is going to let me; it’s who is going to stop me." – Ayn Rand',
  '"It’s not what happens to you, but how you react to it that matters." – Epictetus',
  '"It’s not the load that breaks you down, it’s the way you carry it." – Lou Holtz',
  '"The only place where success comes before work is in the dictionary." – Vidal Sassoon',
  '"It’s never too late to be what you might have been." – George Eliot',
  '"The biggest risk is not taking any risk." – Mark Zuckerberg',
  '"If you really want to do something, you’ll find a way. If you don’t, you’ll find an excuse." – Jim Rohn',
  '"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." – Steve Jobs',
  '"The way to get started is to quit talking and begin doing." – Walt Disney',
  '"Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit." – Conrad Hilton',
  '"Dream big and dare to fail." – Norman Vaughan',
  '"Life isn’t about waiting for the storm to pass, it’s about learning how to dance in the rain." – Vivian Greene',
  '"Don’t be afraid to give up the good to go for the great." – John D. Rockefeller',
  '"It’s not whether you get knocked down, it’s whether you get up." – Vince Lombardi',
  '"If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on." – Sheryl Sandberg',
  '"Failure is another stepping stone to greatness." – Oprah Winfrey',
  '"Success usually comes to those who are too busy to be looking for it." – Henry David Thoreau',
  '"Challenges are what make life interesting and overcoming them is what makes life meaningful." – Joshua J. Marine',
  '"I find that the harder I work, the more luck I seem to have." – Thomas Jefferson',
  '"Success is how high you bounce when you hit bottom." – George S. Patton',
  '"What you do today can improve all your tomorrows." – Ralph Marston',
  '"Success is not the absence of failure; it’s the persistence through failure." – Aisha Tyler',
  '"Believe you can and you’re halfway there." – Theodore Roosevelt',
  '"Perseverance is not a long race; it is many short races one after the other." – Walter Elliot',
  '"The harder the conflict, the more glorious the triumph." – Thomas Paine',
  '"There are no secrets to success. It is the result of preparation, hard work, and learning from failure." – Colin Powell',
  '"What would you attempt to do if you knew you could not fail?" – Robert H. Schuller',
  '"Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do." – Unknown',
  '"The greatest discovery of all time is that a person can change his future by merely changing his attitude." – Oprah Winfrey',
  '"You don’t have to be great to start, but you have to start to be great." – Zig Ziglar',
  '"Success is the sum of small efforts, repeated day in and day out." – Robert Collier',
  '"Don’t wait. The time will never be just right." – Napoleon Hill',
  '"The man who has confidence in himself gains the confidence of others." – Hasidic Proverb',
  '"It always seems impossible until it’s done." – Nelson Mandela',
  '"You can, you should, and if you’re brave enough to start, you will." – Stephen King',
  '"Do not wait to strike till the iron is hot, but make it hot by striking." – William Butler Yeats',
  '"He who conquers himself is the mightiest warrior." – Confucius',
  '"Courage is resistance to fear, mastery of fear—not absence of fear." – Mark Twain',
  '"If you want to achieve greatness stop asking for permission." – Anonymous',
  '"Success is not in what you have, but who you are." – Bo Bennett',
  '"The greatest pleasure in life is doing what people say you cannot do." – Walter Bagehot',
  '"I never dreamed about success, I worked for it." – Estée Lauder',
  '"You only live once, but if you do it right, once is enough." – Mae West',
  '"I am not a product of my circumstances. I am a product of my decisions." – Stephen Covey',
  '"You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals." – Booker T. Washington',
  '"The way to get started is to quit talking and begin doing." – Walt Disney',
  '"Don’t limit your challenges. Challenge your limits." – Anonymous',
  '"Success is not about being the best. It’s about always getting better." – Behdad Sami',
  '"The only way to do great work is to love what you do." – Steve Jobs',
  '"Success is not the key to happiness. Happiness is the key to success." – Albert Schweitzer',
  '"Your life only gets better when you get better." – Brian Tracy',
  '"Don’t be afraid to give up the good to go for the great." – John D. Rockefeller',
  '"To be successful, you must accept all challenges that come your way. You can’t just accept the ones you like." – Mike Gafka',
  '"The only person you should strive to be better than, is the person you were yesterday." – Matty Mullins',
  '"The more you praise and celebrate your life, the more there is in life to celebrate." – Oprah Winfrey',
  '"Success is liking yourself, liking what you do, and liking how you do it." – Maya Angelou',
  '"Always bear in mind that your own resolution to succeed is more important than any other one thing." – Abraham Lincoln',
  '"I am thankful for all of those who said NO to me. It’s because of them I’m doing it myself." – Albert Einstein',
  '"We become what we think about." – Earl Nightingale',
  '"Live as if you were to die tomorrow. Learn as if you were to live forever." – Mahatma Gandhi',
  '"It’s hard to beat a person who never gives up." – Babe Ruth',
  '"When you have a dream, you’ve got to grab it and never let go." – Carol Burnett',
];

module.exports = { quotes: standardQuotes };
