const standardQuotes = [
  '"You must be the change you wish to see in the world." – Mahatma Gandhi',
  '"Opportunities don\'t happen. You create them." – Chris Grosser',
  '"The only impossible journey is the one you never begin." – Tony Robbins',
  '"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart." – Roy T. Bennett',
  '"It always seems impossible until it’s done." – Nelson Mandela',
  '"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact." – William James',
  '"You have within you right now, everything you need to deal with whatever the world can throw at you." – Brian Tracy',
  '"The only way to achieve the impossible is to believe it is possible." – Charles Kingsleigh',
  '"Success is going from failure to failure without losing your enthusiasm." – Winston Churchill',
  '"The only person you are destined to become is the person you decide to be." – Ralph Waldo Emerson',
  '"To live is the rarest thing in the world. Most people exist, that is all." – Oscar Wilde',
  '"Go confidently in the direction of your dreams. Live the life you have imagined." – Henry David Thoreau',
  '"You must do the things you think you cannot do." – Eleanor Roosevelt',
  '"Everything you can imagine is real." – Pablo Picasso',
  '"The mind is everything. What you think you become." – Buddha',
  '"Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. The world is full of educated derelicts. The slogan ‘Press On’ has solved and always will solve the problems of the human race." – Calvin Coolidge',
  '"Don’t let what you cannot do interfere with what you can do." – John Wooden',
  '"The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it." – Jordan Belfort',
  '"The most wasted of days is one without laughter." – E.E. Cummings',
  '"To handle yourself, use your head; to handle others, use your heart." – Eleanor Roosevelt',
  '"The difference between ordinary and extraordinary is that little extra." – Jimmy Johnson',
  '"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle." – Christian D. Larson',
  '"In three words I can sum up everything I\'ve learned about life: it goes on." – Robert Frost',
  '"Life is either a daring adventure or nothing at all." – Helen Keller',
  '"Success doesn’t come from what you do occasionally, it comes from what you do consistently." – Marie Forleo',
  '"The best way out is always through." – Robert Frost',
  '"It is never too late to be what you might have been." – George Eliot',
  '"The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well." – Ralph Waldo Emerson',
  '"In order to succeed, we must first believe that we can." – Nikos Kazantzakis',
  '"We may encounter many defeats but we must not be defeated." – Maya Angelou',
  '"You only live once, but if you do it right, once is enough." – Mae West',
  '"The best time to plant a tree was 20 years ago. The second best time is now." – Chinese Proverb',
  '"Your passion is waiting for your courage to catch up." – Isabelle Lafleche',
  '"A goal is not always meant to be reached, it often serves simply as something to aim at." – Bruce Lee',
  '"The only person you should try to be better than is the person you were yesterday." – Anonymous',
  '"Everything has beauty, but not everyone can see." – Confucius',
  '"Success usually comes to those who are too busy to be looking for it." – Henry David Thoreau',
  '"Your life does not get better by chance, it gets better by change." – Jim Rohn',
  '"The best way to predict the future is to create it." – Peter Drucker',
  '"We can’t help everyone, but everyone can help someone." – Ronald Reagan',
  '"You don’t have to be perfect to be amazing." – Anonymous',
  '"The only way to make sense out of change is to plunge into it, move with it, and join the dance." – Alan Watts',
  '"Be yourself; everyone else is already taken." – Oscar Wilde',
  '"Your time is limited, so don’t waste it living someone else’s life." – Steve Jobs',
  '"Everything has its beauty, but not everyone can see it." – Confucius',
  '"The only limit to our realization of tomorrow is our doubts of today." – Franklin D. Roosevelt',
  '"Do what you can, with what you have, where you are." – Theodore Roosevelt',
  '"You can’t go back and change the beginning, but you can start where you are and change the ending." – C.S. Lewis',
  '"The future belongs to those who believe in the beauty of their dreams." – Eleanor Roosevelt',
  '"Life is what happens when you’re busy making other plans." – John Lennon',
  "\"In the end, it's not the years in your life that count. It's the life in your years.\" – Abraham Lincoln",
  '"Everything you’ve ever wanted is on the other side of fear." – George Addair',
  '"What lies behind us and what lies before us are tiny matters compared to what lies within us." – Ralph Waldo Emerson',
  '"You are never too old to set another goal or to dream a new dream." – C.S. Lewis',
  '"The only way to do great work is to love what you do." – Steve Jobs',
  '"The best way to get started is to quit talking and begin doing." – Walt Disney',
  '"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful." – Albert Schweitzer',
  '"Believe you can and you\'re halfway there." – Theodore Roosevelt',
  '"It does not matter how slowly you go as long as you do not stop." – Confucius',
  '"The best revenge is massive success." – Frank Sinatra',
  '"You must be the change you wish to see in the world." – Mahatma Gandhi',
  '"Opportunities don\'t happen. You create them." – Chris Grosser',
  '"The only impossible journey is the one you never begin." – Tony Robbins',
  '"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart." – Roy T. Bennett',
  '"It always seems impossible until it’s done." – Nelson Mandela',
  '"Be not afraid of life. Believe that life is worth living, and your belief will help create the fact." – William James',
  '"You have within you right now, everything you need to deal with whatever the world can throw at you." – Brian Tracy',
  '"The only way to achieve the impossible is to believe it is possible." – Charles Kingsleigh',
  '"Success is going from failure to failure without losing your enthusiasm." – Winston Churchill',
  '"The only person you are destined to become is the person you decide to be." – Ralph Waldo Emerson',
  '"To live is the rarest thing in the world. Most people exist, that is all." – Oscar Wilde',
  '"Go confidently in the direction of your dreams. Live the life you have imagined." – Henry David Thoreau',
  '"You must do the things you think you cannot do." – Eleanor Roosevelt',
  '"Everything you can imagine is real." – Pablo Picasso',
  '"The mind is everything. What you think you become." – Buddha',
  '"Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. The world is full of educated derelicts. The slogan ‘Press On’ has solved and always will solve the problems of the human race." – Calvin Coolidge',
  '"Don’t let what you cannot do interfere with what you can do." – John Wooden',
  '"The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it." – Jordan Belfort',
  '"The most wasted of days is one without laughter." – E.E. Cummings',
  '"To handle yourself, use your head; to handle others, use your heart." – Eleanor Roosevelt',
  '"The difference between ordinary and extraordinary is that little extra." – Jimmy Johnson',
  '"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle." – Christian D. Larson',
  '"In three words I can sum up everything I\'ve learned about life: it goes on." – Robert Frost',
  '"Life is either a daring adventure or nothing at all." – Helen Keller',
  '"Success doesn’t come from what you do occasionally, it comes from what you do consistently." – Marie Forleo',
  '"The best way out is always through." – Robert Frost',
  '"It is never too late to be what you might have been." – George Eliot',
  '"The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well." – Ralph Waldo Emerson',
];

module.exports = { standardQuotes };
